// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"
)

type Follower struct {
	UserID     int32
	FollowerID int32
}

type Publication struct {
	ID        int32
	Title     string
	Content   string
	AuthorID  int32
	Likes     sql.NullInt32
	CreatedAt sql.NullTime
}

type User struct {
	ID        int32
	Name      string
	Nick      string
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
